### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by aneopsy** [SR-G/bambu-lab-observer#1]
Hello,
Thank you for your project, If you need help, I'm a software engineer.

The program is able to connect to the mqqt but once it receive a message it crash.

config:
`{
    "BambuLabPrinters" : [ 
        {
          "IP" : "192.168.XXX.XXX",
          "Disabled" : false,
          "MQTTTLS" : true,
          "MQTTUsername" : "bblp",
          "MQTTPassword" : "XXXXX"
        }
    ],
    "CSVFileName" : "bambu-lab-observer.csv",
    "LogLevel" : "INFO",
    "Topics" : [ "device/+/report" ],
    "PolicyAboutRegisterStartOfPrint" : "FIRST_MESSAGE_TIMESTAMP"
}`

I tested **windows_386** and **windows_amd64** program
printer: X1C firmware: **v.01.06.05.00**

**Comment by SR-G** [comment]
Yeah, indeed, this is happening since 01.06.05.00 (and later) firmware, i updated the program on my side (new messages are pushed by the printer since that time) - i'll upload ASAP the new version.

**Comment by SR-G** [comment]
Corrected with 1.0.2-SNAPSHOT (still a pre-release)
https://github.com/SR-G/bambu-lab-observer/releases/tag/1.0.2-SNAPSHOT

**Comment by aneopsy** [comment]
Thank you

**Comment by aneopsy** [comment]
Is it possible to make the project open source? I'd like to write the documentation around MQTT command/info for bambulab printers.
