### ISSUE TITLE
Open Sourcing Code

### ISSUE THREAD

**Issue by enly1** [SR-G/bambu-lab-observer#3]
Hi, 

I am considering doing some stuff with the MQTT and would love to avoid re-inventing the wheel and reversing the messages again.

Can you upload the code - understand it may not be pretty, but even if its a burner branch, would be good to share so others can build on your work ?

Just an ask.

Simon

**Comment by ojarva** [comment]
So... this repository is abandonware now, isn't it?

**Comment by SR-G** [comment]
No.

**Comment by ojarva** [comment]
It certainly looks like so, considering there's no content or any kind of progress. 🤷‍♂️
